### ISSUE TITLE
What are best possible ways to test Restful web services?

### ISSUE THREAD

**Issue by kadimulam** [smartrics/RestFixtureLiveDoc#1]
What are best possible ways to test Restful web services, with a minimal wiki code that a BA/QA user can write? With the RestFixture, the user currently needs to write the HTTP methods, Headers, URI, Request and Response which might not be that user friendly for BQ/QA user. Moreover, this has to be repeated for every HTTP verb they are willing to test. Do you have any suggestions?

**Comment by smartrics** [comment]
The focus - with RestFixture - is the API and the "live documentation" of the system under test.
If live documentation of the API is not the primary concern then you may want to use other tools.
That is, if the end user of your system is not another programmatic client using the API, but rather - say - a human using a web UI, you may want to use other tools like selenium.
